services:
  robots-figma:
    build:
      target: dev
    image: robots-figma:dev
    environment:
      - NODE_ENV=development
    command: ["npm", "start"]
    volumes:
      - .:/app
      - /app/node_modules
