services:
  robots-figma:
    image: robots-figma:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--openssl-legacy-provider
    volumes:
      - .:/app # Bind Mount the current directory to /app in the container
      - /app/node_modules # Avoids conflicts with host's node_modules
